package com.example.diary;

import androidx.appcompat.app.AppCompatActivity;

import android.content.ContentValues;
import android.content.Intent;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.os.Bundle;
import android.view.View;
import android.widget.ImageButton;
import android.widget.Toast;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ImageButton button = (ImageButton) findViewById(R.id.btnToDiary);
        ImageButton button2 = (ImageButton) findViewById(R.id.btn_to_dz);
        View.OnClickListener listener =  new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                switch (v.getId()) {
                    case R.id.btnToDiary:
                        try{
                            SQLiteDatabase mybase = openOrCreateDatabase("cache.txt",MODE_PRIVATE,null);
                            mybase.execSQL("CREATE TABLE IF NOT EXISTS use(day VARCHAR(5), lesson VARCHAR(20), cabinet VARCHAR(10), time VARCHAR(15))");
                            Toast.makeText(getApplicationContext(),"open base",Toast.LENGTH_SHORT);
                            Cursor cursor = mybase.rawQuery("select day, lesson, cabinet, time from use", null);
                            if (cursor.moveToNext()){
                                Toast.makeText(getApplicationContext(),"Found!",Toast.LENGTH_SHORT);
                                cursor.close();
                                mybase.close();
                                Intent i = new Intent(MainActivity.this, Timetable.class);
                                startActivity(i);
                                break;
                            }
                            else {
                                ContentValues mon_str1 = new ContentValues();
                                mon_str1.put("day", "mo1");
                                mon_str1.put("lesson", "");
                                mon_str1.put("cabinet", "");
                                mon_str1.put("time", "");
                                ContentValues mon_str2 = new ContentValues();
                                mon_str2.put("day", "mo2");
                                mon_str2.put("lesson", "");
                                mon_str2.put("cabinet", "");
                                mon_str2.put("time", "");
                                ContentValues mon_str3 = new ContentValues();
                                mon_str3.put("day", "mo3");
                                mon_str3.put("lesson", "");
                                mon_str3.put("cabinet", "");
                                mon_str3.put("time", "");
                                ContentValues mon_str4 = new ContentValues();
                                mon_str4.put("day", "mo4");
                                mon_str4.put("lesson", "");
                                mon_str4.put("cabinet", "");
                                mon_str4.put("time", "");
                                ContentValues mon_str5 = new ContentValues();
                                mon_str5.put("day", "mo5");
                                mon_str5.put("lesson", "");
                                mon_str5.put("cabinet", "");
                                mon_str5.put("time", "");
                                ContentValues mon_str6 = new ContentValues();
                                mon_str6.put("day", "mo6");
                                mon_str6.put("lesson", "");
                                mon_str6.put("cabinet", "");
                                mon_str6.put("time", "");
                                ContentValues mon_str7 = new ContentValues();
                                mon_str7.put("day", "mo7");
                                mon_str7.put("lesson", "");
                                mon_str7.put("cabinet", "");
                                mon_str7.put("time", "");
                                ContentValues mon_str8 = new ContentValues();
                                mon_str8.put("day", "mo8");
                                mon_str8.put("lesson", "");
                                mon_str8.put("cabinet", "");
                                mon_str8.put("time", "");
                                ContentValues mon_str9 = new ContentValues();
                                mon_str9.put("day", "mo9");
                                mon_str9.put("lesson", "");
                                mon_str9.put("cabinet", "");
                                mon_str9.put("time", "");
                                ContentValues mon_str10 = new ContentValues();
                                mon_str10.put("day", "mo0");
                                mon_str10.put("lesson", "");
                                mon_str10.put("cabinet", "");
                                mon_str10.put("time", "");
                                ContentValues mon_str11 = new ContentValues();
                                mon_str11.put("day", "mo_");
                                mon_str11.put("lesson", "");
                                mon_str11.put("cabinet", "");
                                mon_str11.put("time", "");
                                ContentValues mon_str12 = new ContentValues();
                                mon_str12.put("day", "mon");
                                mon_str12.put("lesson", "");
                                mon_str12.put("cabinet", "");
                                mon_str12.put("time", "");

                                ContentValues tue_str1 = new ContentValues();
                                tue_str1.put("day", "tu1");
                                tue_str1.put("lesson", "");
                                tue_str1.put("cabinet", "");
                                tue_str1.put("time", "");
                                ContentValues tue_str2 = new ContentValues();
                                tue_str2.put("day", "tu2");
                                tue_str2.put("lesson", "");
                                tue_str2.put("cabinet", "");
                                tue_str2.put("time", "");
                                ContentValues tue_str3 = new ContentValues();
                                tue_str3.put("day", "tu3");
                                tue_str3.put("lesson", "");
                                tue_str3.put("cabinet", "");
                                tue_str3.put("time", "");
                                ContentValues tue_str4 = new ContentValues();
                                tue_str4.put("day", "tu4");
                                tue_str4.put("lesson", "");
                                tue_str4.put("cabinet", "");
                                tue_str4.put("time", "");
                                ContentValues tue_str5 = new ContentValues();
                                tue_str5.put("day", "tu5");
                                tue_str5.put("lesson", "");
                                tue_str5.put("cabinet", "");
                                tue_str5.put("time", "");
                                ContentValues tue_str6 = new ContentValues();
                                tue_str6.put("day", "tu6");
                                tue_str6.put("lesson", "");
                                tue_str6.put("cabinet", "");
                                tue_str6.put("time", "");
                                ContentValues tue_str7 = new ContentValues();
                                tue_str7.put("day", "tu7");
                                tue_str7.put("lesson", "");
                                tue_str7.put("cabinet", "");
                                tue_str7.put("time", "");
                                ContentValues tue_str8 = new ContentValues();
                                tue_str8.put("day", "tu8");
                                tue_str8.put("lesson", "");
                                tue_str8.put("cabinet", "");
                                tue_str8.put("time", "");
                                ContentValues tue_str9 = new ContentValues();
                                tue_str9.put("day", "tu9");
                                tue_str9.put("lesson", "");
                                tue_str9.put("cabinet", "");
                                tue_str9.put("time", "");
                                ContentValues tue_str10 = new ContentValues();
                                tue_str10.put("day", "tu0");
                                tue_str10.put("lesson", "");
                                tue_str10.put("cabinet", "");
                                tue_str10.put("time", "");
                                ContentValues tue_str11 = new ContentValues();
                                tue_str11.put("day", "tu_");
                                tue_str11.put("lesson", "");
                                tue_str11.put("cabinet", "");
                                tue_str11.put("time", "");
                                ContentValues tue_str12 = new ContentValues();
                                tue_str12.put("day", "tun");
                                tue_str12.put("lesson", "");
                                tue_str12.put("cabinet", "");
                                tue_str12.put("time", "");

                                ContentValues wed_str1 = new ContentValues();
                                wed_str1.put("day", "we1");
                                wed_str1.put("lesson", "");
                                wed_str1.put("cabinet", "");
                                wed_str1.put("time", "");
                                ContentValues wed_str2 = new ContentValues();
                                wed_str2.put("day", "we2");
                                wed_str2.put("lesson", "");
                                wed_str2.put("cabinet", "");
                                wed_str2.put("time", "");
                                ContentValues wed_str3 = new ContentValues();
                                wed_str3.put("day", "we3");
                                wed_str3.put("lesson", "");
                                wed_str3.put("cabinet", "");
                                wed_str3.put("time", "");
                                ContentValues wed_str4 = new ContentValues();
                                wed_str4.put("day", "we4");
                                wed_str4.put("lesson", "");
                                wed_str4.put("cabinet", "");
                                wed_str4.put("time", "");
                                ContentValues wed_str5 = new ContentValues();
                                wed_str5.put("day", "we5");
                                wed_str5.put("lesson", "");
                                wed_str5.put("cabinet", "");
                                wed_str5.put("time", "");
                                ContentValues wed_str6 = new ContentValues();
                                wed_str6.put("day", "we6");
                                wed_str6.put("lesson", "");
                                wed_str6.put("cabinet", "");
                                wed_str6.put("time", "");
                                ContentValues wed_str7 = new ContentValues();
                                wed_str7.put("day", "we7");
                                wed_str7.put("lesson", "");
                                wed_str7.put("cabinet", "");
                                wed_str7.put("time", "");
                                ContentValues wed_str8 = new ContentValues();
                                wed_str8.put("day", "we8");
                                wed_str8.put("lesson", "");
                                wed_str8.put("cabinet", "");
                                wed_str8.put("time", "");
                                ContentValues wed_str9 = new ContentValues();
                                wed_str9.put("day", "we9");
                                wed_str9.put("lesson", "");
                                wed_str9.put("cabinet", "");
                                wed_str9.put("time", "");
                                ContentValues wed_str10 = new ContentValues();
                                wed_str10.put("day", "we0");
                                wed_str10.put("lesson", "");
                                wed_str10.put("cabinet", "");
                                wed_str10.put("time", "");
                                ContentValues wed_str11 = new ContentValues();
                                wed_str11.put("day", "we_");
                                wed_str11.put("lesson", "");
                                wed_str11.put("cabinet", "");
                                wed_str11.put("time", "");
                                ContentValues wed_str12 = new ContentValues();
                                wed_str12.put("day", "wen");
                                wed_str12.put("lesson", "");
                                wed_str12.put("cabinet", "");
                                wed_str12.put("time", "");

                                ContentValues thu_str1 = new ContentValues();
                                thu_str1.put("day", "th1");
                                thu_str1.put("lesson", "");
                                thu_str1.put("cabinet", "");
                                thu_str1.put("time", "");
                                ContentValues thu_str2 = new ContentValues();
                                thu_str2.put("day", "th2");
                                thu_str2.put("lesson", "");
                                thu_str2.put("cabinet", "");
                                thu_str2.put("time", "");
                                ContentValues thu_str3 = new ContentValues();
                                thu_str3.put("day", "th3");
                                thu_str3.put("lesson", "");
                                thu_str3.put("cabinet", "");
                                thu_str3.put("time", "");
                                ContentValues thu_str4 = new ContentValues();
                                thu_str4.put("day", "th4");
                                thu_str4.put("lesson", "");
                                thu_str4.put("cabinet", "");
                                thu_str4.put("time", "");
                                ContentValues thu_str5 = new ContentValues();
                                thu_str5.put("day", "th5");
                                thu_str5.put("lesson", "");
                                thu_str5.put("cabinet", "");
                                thu_str5.put("time", "");
                                ContentValues thu_str6 = new ContentValues();
                                thu_str6.put("day", "th6");
                                thu_str6.put("lesson", "");
                                thu_str6.put("cabinet", "");
                                thu_str6.put("time", "");
                                ContentValues thu_str7 = new ContentValues();
                                thu_str7.put("day", "th7");
                                thu_str7.put("lesson", "");
                                thu_str7.put("cabinet", "");
                                thu_str7.put("time", "");
                                ContentValues thu_str8 = new ContentValues();
                                thu_str8.put("day", "th8");
                                thu_str8.put("lesson", "");
                                thu_str8.put("cabinet", "");
                                thu_str8.put("time", "");
                                ContentValues thu_str9 = new ContentValues();
                                thu_str9.put("day", "th9");
                                thu_str9.put("lesson", "");
                                thu_str9.put("cabinet", "");
                                thu_str9.put("time", "");
                                ContentValues thu_str10 = new ContentValues();
                                thu_str10.put("day", "th0");
                                thu_str10.put("lesson", "");
                                thu_str10.put("cabinet", "");
                                thu_str10.put("time", "");
                                ContentValues thu_str11 = new ContentValues();
                                thu_str11.put("day", "th_");
                                thu_str11.put("lesson", "");
                                thu_str11.put("cabinet", "");
                                thu_str11.put("time", "");
                                ContentValues thu_str12 = new ContentValues();
                                thu_str12.put("day", "thn");
                                thu_str12.put("lesson", "");
                                thu_str12.put("cabinet", "");
                                thu_str12.put("time", "");

                                ContentValues fri_str1 = new ContentValues();
                                fri_str1.put("day", "fr1");
                                fri_str1.put("lesson", "");
                                fri_str1.put("cabinet", "");
                                fri_str1.put("time", "");
                                ContentValues fri_str2 = new ContentValues();
                                fri_str2.put("day", "fr2");
                                fri_str2.put("lesson", "");
                                fri_str2.put("cabinet", "");
                                fri_str2.put("time", "");
                                ContentValues fri_str3 = new ContentValues();
                                fri_str3.put("day", "fr3");
                                fri_str3.put("lesson", "");
                                fri_str3.put("cabinet", "");
                                fri_str3.put("time", "");
                                ContentValues fri_str4 = new ContentValues();
                                fri_str4.put("day", "fr4");
                                fri_str4.put("lesson", "");
                                fri_str4.put("cabinet", "");
                                fri_str4.put("time", "");
                                ContentValues fri_str5 = new ContentValues();
                                fri_str5.put("day", "fr5");
                                fri_str5.put("lesson", "");
                                fri_str5.put("cabinet", "");
                                fri_str5.put("time", "");
                                ContentValues fri_str6 = new ContentValues();
                                fri_str6.put("day", "fr6");
                                fri_str6.put("lesson", "");
                                fri_str6.put("cabinet", "");
                                fri_str6.put("time", "");
                                ContentValues fri_str7 = new ContentValues();
                                fri_str7.put("day", "fr7");
                                fri_str7.put("lesson", "");
                                fri_str7.put("cabinet", "");
                                fri_str7.put("time", "");
                                ContentValues fri_str8 = new ContentValues();
                                fri_str8.put("day", "fr8");
                                fri_str8.put("lesson", "");
                                fri_str8.put("cabinet", "");
                                fri_str8.put("time", "");
                                ContentValues fri_str9 = new ContentValues();
                                fri_str9.put("day", "fr9");
                                fri_str9.put("lesson", "");
                                fri_str9.put("cabinet", "");
                                fri_str9.put("time", "");
                                ContentValues fri_str10 = new ContentValues();
                                fri_str10.put("day", "fr0");
                                fri_str10.put("lesson", "");
                                fri_str10.put("cabinet", "");
                                fri_str10.put("time", "");
                                ContentValues fri_str11 = new ContentValues();
                                fri_str11.put("day", "fr_");
                                fri_str11.put("lesson", "");
                                fri_str11.put("cabinet", "");
                                fri_str11.put("time", "");
                                ContentValues fri_str12 = new ContentValues();
                                fri_str12.put("day", "frn");
                                fri_str12.put("lesson", "");
                                fri_str12.put("cabinet", "");
                                fri_str12.put("time", "");

                                ContentValues sat_str1 = new ContentValues();
                                sat_str1.put("day", "sa1");
                                sat_str1.put("lesson", "");
                                sat_str1.put("cabinet", "");
                                sat_str1.put("time", "");
                                ContentValues sat_str2 = new ContentValues();
                                sat_str2.put("day", "sa2");
                                sat_str2.put("lesson", "");
                                sat_str2.put("cabinet", "");
                                sat_str2.put("time", "");
                                ContentValues sat_str3 = new ContentValues();
                                sat_str3.put("day", "sa3");
                                sat_str3.put("lesson", "");
                                sat_str3.put("cabinet", "");
                                sat_str3.put("time", "");
                                ContentValues sat_str4 = new ContentValues();
                                sat_str4.put("day", "sa4");
                                sat_str4.put("lesson", "");
                                sat_str4.put("cabinet", "");
                                sat_str4.put("time", "");
                                ContentValues sat_str5 = new ContentValues();
                                sat_str5.put("day", "sa5");
                                sat_str5.put("lesson", "");
                                sat_str5.put("cabinet", "");
                                sat_str5.put("time", "");
                                ContentValues sat_str6 = new ContentValues();
                                sat_str6.put("day", "sa6");
                                sat_str6.put("lesson", "");
                                sat_str6.put("cabinet", "");
                                sat_str6.put("time", "");
                                ContentValues sat_str7 = new ContentValues();
                                sat_str7.put("day", "sa7");
                                sat_str7.put("lesson", "");
                                sat_str7.put("cabinet", "");
                                sat_str7.put("time", "");
                                ContentValues sat_str8 = new ContentValues();
                                sat_str8.put("day", "sa8");
                                sat_str8.put("lesson", "");
                                sat_str8.put("cabinet", "");
                                sat_str8.put("time", "");
                                ContentValues sat_str9 = new ContentValues();
                                sat_str9.put("day", "sa9");
                                sat_str9.put("lesson", "");
                                sat_str9.put("cabinet", "");
                                sat_str9.put("time", "");
                                ContentValues sat_str10 = new ContentValues();
                                sat_str10.put("day", "sa0");
                                sat_str10.put("lesson", "");
                                sat_str10.put("cabinet", "");
                                sat_str10.put("time", "");
                                ContentValues sat_str11 = new ContentValues();
                                sat_str11.put("day", "sa_");
                                sat_str11.put("lesson", "");
                                sat_str11.put("cabinet", "");
                                sat_str11.put("time", "");
                                ContentValues sat_str12 = new ContentValues();
                                sat_str12.put("day", "san");
                                sat_str12.put("lesson", "");
                                sat_str12.put("cabinet", "");
                                sat_str12.put("time", "");

                                ContentValues sun_str1 = new ContentValues();
                                sun_str1.put("day", "su1");
                                sun_str1.put("lesson", "");
                                sun_str1.put("cabinet", "");
                                sun_str1.put("time", "");
                                ContentValues sun_str2 = new ContentValues();
                                sun_str2.put("day", "su2");
                                sun_str2.put("lesson", "");
                                sun_str2.put("cabinet", "");
                                sun_str2.put("time", "");
                                ContentValues sun_str3 = new ContentValues();
                                sun_str3.put("day", "su3");
                                sun_str3.put("lesson", "");
                                sun_str3.put("cabinet", "");
                                sun_str3.put("time", "");
                                ContentValues sun_str4 = new ContentValues();
                                sun_str4.put("day", "su4");
                                sun_str4.put("lesson", "");
                                sun_str4.put("cabinet", "");
                                sun_str4.put("time", "");
                                ContentValues sun_str5 = new ContentValues();
                                sun_str5.put("day", "su5");
                                sun_str5.put("lesson", "");
                                sun_str5.put("cabinet", "");
                                sun_str5.put("time", "");
                                ContentValues sun_str6 = new ContentValues();
                                sun_str6.put("day", "su6");
                                sun_str6.put("lesson", "");
                                sun_str6.put("cabinet", "");
                                sun_str6.put("time", "");
                                ContentValues sun_str7 = new ContentValues();
                                sun_str7.put("day", "su7");
                                sun_str7.put("lesson", "");
                                sun_str7.put("cabinet", "");
                                sun_str7.put("time", "");
                                ContentValues sun_str8 = new ContentValues();
                                sun_str8.put("day", "su8");
                                sun_str8.put("lesson", "");
                                sun_str8.put("cabinet", "");
                                sun_str8.put("time", "");
                                ContentValues sun_str9 = new ContentValues();
                                sun_str9.put("day", "su9");
                                sun_str9.put("lesson", "");
                                sun_str9.put("cabinet", "");
                                sun_str9.put("time", "");
                                ContentValues sun_str10 = new ContentValues();
                                sun_str10.put("day", "su0");
                                sun_str10.put("lesson", "");
                                sun_str10.put("cabinet", "");
                                sun_str10.put("time", "");
                                ContentValues sun_str11 = new ContentValues();
                                sun_str11.put("day", "su_");
                                sun_str11.put("lesson", "");
                                sun_str11.put("cabinet", "");
                                sun_str11.put("time", "");
                                ContentValues sun_str12 = new ContentValues();
                                sun_str12.put("day", "sun");
                                sun_str12.put("lesson", "");
                                sun_str12.put("cabinet", "");
                                sun_str12.put("time", "");

                                mybase.insert("use", null, mon_str1);
                                mybase.insert("use", null, mon_str2);
                                mybase.insert("use", null, mon_str3);
                                mybase.insert("use", null, mon_str4);
                                mybase.insert("use", null, mon_str5);
                                mybase.insert("use", null, mon_str6);
                                mybase.insert("use", null, mon_str7);
                                mybase.insert("use", null, mon_str8);
                                mybase.insert("use", null, mon_str9);
                                mybase.insert("use", null, mon_str10);
                                mybase.insert("use", null, mon_str11);
                                mybase.insert("use", null, mon_str12);

                                mybase.insert("use", null, tue_str1);
                                mybase.insert("use", null, tue_str2);
                                mybase.insert("use", null, tue_str3);
                                mybase.insert("use", null, tue_str4);
                                mybase.insert("use", null, tue_str5);
                                mybase.insert("use", null, tue_str6);
                                mybase.insert("use", null, tue_str7);
                                mybase.insert("use", null, tue_str8);
                                mybase.insert("use", null, tue_str9);
                                mybase.insert("use", null, tue_str10);
                                mybase.insert("use", null, tue_str11);
                                mybase.insert("use", null, tue_str12);

                                mybase.insert("use", null, wed_str1);
                                mybase.insert("use", null, wed_str2);
                                mybase.insert("use", null, wed_str3);
                                mybase.insert("use", null, wed_str4);
                                mybase.insert("use", null, wed_str5);
                                mybase.insert("use", null, wed_str6);
                                mybase.insert("use", null, wed_str7);
                                mybase.insert("use", null, wed_str8);
                                mybase.insert("use", null, wed_str9);
                                mybase.insert("use", null, wed_str10);
                                mybase.insert("use", null, wed_str11);
                                mybase.insert("use", null, wed_str12);

                                mybase.insert("use", null, thu_str1);
                                mybase.insert("use", null, thu_str2);
                                mybase.insert("use", null, thu_str3);
                                mybase.insert("use", null, thu_str4);
                                mybase.insert("use", null, thu_str5);
                                mybase.insert("use", null, thu_str6);
                                mybase.insert("use", null, thu_str7);
                                mybase.insert("use", null, thu_str8);
                                mybase.insert("use", null, thu_str9);
                                mybase.insert("use", null, thu_str10);
                                mybase.insert("use", null, thu_str11);
                                mybase.insert("use", null, thu_str12);

                                mybase.insert("use", null, fri_str1);
                                mybase.insert("use", null, fri_str2);
                                mybase.insert("use", null, fri_str3);
                                mybase.insert("use", null, fri_str4);
                                mybase.insert("use", null, fri_str5);
                                mybase.insert("use", null, fri_str6);
                                mybase.insert("use", null, fri_str7);
                                mybase.insert("use", null, fri_str8);
                                mybase.insert("use", null, fri_str9);
                                mybase.insert("use", null, fri_str10);
                                mybase.insert("use", null, fri_str11);
                                mybase.insert("use", null, fri_str12);

                                mybase.insert("use", null, sat_str1);
                                mybase.insert("use", null, sat_str2);
                                mybase.insert("use", null, sat_str3);
                                mybase.insert("use", null, sat_str4);
                                mybase.insert("use", null, sat_str5);
                                mybase.insert("use", null, sat_str6);
                                mybase.insert("use", null, sat_str7);
                                mybase.insert("use", null, sat_str8);
                                mybase.insert("use", null, sat_str9);
                                mybase.insert("use", null, sat_str10);
                                mybase.insert("use", null, sat_str11);
                                mybase.insert("use", null, sat_str12);

                                mybase.insert("use", null, sun_str1);
                                mybase.insert("use", null, sun_str2);
                                mybase.insert("use", null, sun_str3);
                                mybase.insert("use", null, sun_str4);
                                mybase.insert("use", null, sun_str5);
                                mybase.insert("use", null, sun_str6);
                                mybase.insert("use", null, sun_str7);
                                mybase.insert("use", null, sun_str8);
                                mybase.insert("use", null, sun_str9);
                                mybase.insert("use", null, sun_str10);
                                mybase.insert("use", null, sun_str11);
                                mybase.insert("use", null, sun_str12);

                                cursor.close();
                                mybase.close();
                            }
                            Intent i = new Intent(MainActivity.this, Timetable.class);
                            startActivity(i);
                            break;
                        }catch (Exception e){
                            Toast.makeText(getApplicationContext(),"Что-то пошло не так",Toast.LENGTH_SHORT).show();
                        }
                    case R.id.btn_to_dz:
                        Intent i = new Intent(MainActivity.this, DZ.class);
                        startActivity(i);
                        break;
                }
            }
        };
        button.setOnClickListener(listener);
        button2.setOnClickListener(listener);
    }
}
